# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-10-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=200)),
                ('text', models.TextField()),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='latest')),
                ('person', models.CharField(blank=True, max_length=50, verbose_name='Kirinyagan')),
                ('occupation', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'Kirinyagans Speaks',
                'verbose_name_plural': 'Kirinyagans Speaks',
            },
        ),
    ]
