# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created', models.DateTimeField()),
                ('slug', models.SlugField(default='latest', unique_for_date='created')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='latest')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created', models.DateTimeField()),
                ('slug', models.SlugField(default='latest', unique_for_date='created')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='latest')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
