# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-22 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180722_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Happen',
            new_name='Event',
        ),
    ]
