# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-30 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180722_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
