# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField()),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='latest')),
                ('person', models.CharField(blank=True, max_length=50, verbose_name='Testimonial From')),
                ('course', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
