# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-10-09 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_latest_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest',
            name='tags',
        ),
    ]
