# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-10-05 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirinyaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'Activities'},
        ),
    ]
