# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-10-09 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirinyaga', '0004_auto_20211008_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=200),
        ),
        migrations.AddField(
            model_name='stay',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=200),
        ),
    ]
